# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [ ]:
# Why does my heatmap not showing correctly?
# Why does marker not working correctly?

In [9]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [30]:
weather_data = pd.read_csv("../WeatherPy/weather_data.csv")
weather_data

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,East London,90,ZA,1579453770,88,-33.02,27.91,64.40,6.93
1,George Town,20,MY,1579453844,100,5.41,100.34,80.60,3.53
2,Busselton,0,AU,1579453829,42,-33.65,115.33,66.00,13.13
3,Prince Rupert,40,CA,1579454017,80,54.32,-130.32,39.20,11.41
4,Ribeira Grande,75,PT,1579454018,82,38.52,-28.70,66.20,16.11
...,...,...,...,...,...,...,...,...,...
564,Port-Gentil,20,GA,1579454092,74,-0.72,8.78,86.00,9.17
565,Cockburn Town,0,TC,1579454092,73,21.46,-71.14,75.31,20.87
566,Imbituba,40,BR,1579454092,58,-28.24,-48.67,84.20,11.41
567,Sawakin,94,SD,1579454092,76,19.11,37.33,73.06,18.32
568,Najran,0,SA,1579453921,14,17.49,44.13,75.20,6.93

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [11]:
# Configure gmaps
gmaps.configure(api_key=g_key)

# Store latitude and longitude in locations
locations = weather_data[["Lat", "Lng"]]

# Store Humidity in humidity
humidity = weather_data["Humidity"]

In [28]:
# Customize the size of the figure
figure_layout = {
    'width': '400px',
    'height': '300px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
fig = gmaps.figure(layout = figure_layout)

In [33]:
# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights = humidity,  dissipating=False, max_intensity=10, point_radius=1)

# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [24]:
# Narrow down the cities with wind speed less than 10 mph, cloudiness less than 20 and max temp between 50 and 90
narrowed_city_df = weather_data.loc[(weather_data["Wind Speed"] <= 10) & (weather_data["Cloudiness"] <= 20) & \
                                   (weather_data["Max Temp"] > 50) & (weather_data["Max Temp"] < 90)].dropna()

narrowed_city_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
1,George Town,20,MY,1579453844,100,5.41,100.34,80.60,3.53
5,Porto-Novo,20,BJ,1579454018,70,6.50,2.60,87.80,8.05
7,Esperance,3,AU,1579454018,76,-33.87,121.90,57.20,6.93
14,Kidal,0,ML,1579454019,19,18.44,1.41,68.61,8.68
15,Sao Filipe,5,CV,1579454019,74,14.90,-24.50,71.85,7.96
37,Danane,9,CI,1579454022,21,7.26,-8.15,84.76,2.77
40,Kirakira,13,SB,1579454022,83,-10.45,161.92,75.74,4.21
54,Buala,16,SB,1579454024,84,-8.14,159.59,78.71,7.45
60,Ahipara,0,NZ,1579454025,100,-35.17,173.17,60.01,3.00
67,Honiara,20,SB,1579454026,94,-9.43,159.95,75.20,3.36
73,Cabo San Lucas,5,MX,1579453901,60,22.89,-109.91,75.00,5.23
103,Tizimin,5,MX,1579454030,58,21.15,-88.15,82.40,9.17
144,Araouane,0,ML,1579454036,15,18.90,-3.53,70.25,5.97
164,Mankono,0,CI,1579454038,15,8.06,-6.19,89.47,3.13
165,Kathu,20,TH,1579454039,83,7.92,98.33,78.80,3.36
175,Guerrero Negro,0,MX,1579454040,28,27.98,-114.06,66.58,2.77
176,Katsuura,18,JP,1579454040,81,35.13,140.30,51.01,6.93
184,Arlit,0,NE,1579454041,16,18.74,7.39,70.54,7.72
203,Bousse,3,BF,1579454044,15,12.66,-1.89,87.80,5.82
227,Rach Gia,20,VN,1579454045,83,10.02,105.08,77.00,9.17
232,Salalah,20,OM,1579453854,60,17.02,54.09,75.20,4.70
237,Jieshi,0,CN,1579454049,71,22.81,115.83,57.99,1.01
255,Karimnagar,19,IN,1579454052,69,18.43,79.15,70.77,2.08
262,Bhadrak,0,IN,1579454053,61,21.06,86.51,68.49,2.04
320,Taoudenni,0,ML,1579454061,18,22.68,-3.98,65.82,4.25
325,Kattivakkam,20,IN,1579454061,74,13.22,80.32,78.80,4.70
337,Saint George,1,US,1579454063,64,37.10,-113.58,51.80,6.93
338,Agua Prieta,1,MX,1579454063,39,31.30,-109.57,59.00,4.97
339,Kitale,0,KE,1579454063,62,1.02,35.01,62.42,1.81
344,Bilma,0,NE,1579454064,28,18.69,12.92,63.82,7.25
351,Nikki,0,BJ,1579454065,16,9.94,3.21,83.46,4.52
357,Caramay,1,PH,1579454066,89,10.18,119.24,73.54,5.79
360,Ilo,12,PE,1579454066,88,-17.64,-71.34,72.05,0.76
362,Hithadhoo,10,MV,1579454066,75,-0.60,73.08,83.16,8.39
363,Dhali,20,IN,1579454066,65,10.50,77.17,77.00,4.70
366,Naco,1,MX,1579454067,39,31.33,-109.95,59.00,4.70
380,Sakakah,20,SA,1579454068,43,29.97,40.21,55.40,4.70
385,Bassar,7,TG,1579454069,14,9.25,0.78,87.80,6.93
393,Amlapura,20,ID,1579454070,83,-8.45,115.62,82.40,6.93
394,Rio Grande,20,BR,1579454070,62,-32.03,-52.10,86.00,9.17
407,Lumphat,0,KH,1579454072,67,13.49,106.98,68.22,9.35
409,Keti Bandar,0,PK,1579454072,34,24.14,67.45,64.83,3.98
428,Yola,0,NG,1579454075,24,9.20,12.48,79.05,2.82
441,Aswan,0,EG,1579454076,37,24.09,32.91,62.60,9.17
459,Natitingou,0,BJ,1579454079,14,10.30,1.38,87.80,6.93
468,Whitianga,0,NZ,1579454080,90,-36.83,175.70,59.00,4.29
471,Marsaxlokk,20,MT,1579453992,71,35.84,14.54,57.00,2.24
494,Bamnet Narong,1,TH,1579454083,54,15.50,101.69,73.09,7.05
502,Anloga,20,GH,1579454020,66,5.79,0.90,87.80,8.05
507,Yangjiang,18,CN,1579454085,79,21.85,111.97,55.04,3.56
510,Perth,0,AU,1579453880,68,-31.93,115.83,66.20,8.05
528,Cam Ranh,20,VN,1579454087,69,11.92,109.16,77.00,9.17
534,Marzuq,4,YE,1579454088,79,14.40,46.47,58.53,3.91
538,Cangucu,20,BR,1579454089,62,-31.39,-52.68,86.00,9.17
545,Amalapuram,20,IN,1579454089,74,16.58,82.02,78.80,5.82
564,Port-Gentil,20,GA,1579454092,74,-0.72,8.78,86.00,9.17
568,Najran,0,SA,1579453921,14,17.49,44.13,75.20,6.93

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [20]:
hotel_df = narrowed_city_df[["City", "Lat", "Lng"]].reset_index()
hotel_df["Hotel Name"] = ""

hotel_df

    index            City    Lat     Lng Hotel Name
0       7       Esperance -33.87  121.90
1      14           Kidal  18.44    1.41
2      15      Sao Filipe  14.90  -24.50
3      37          Danane   7.26   -8.15
4      40        Kirakira -10.45  161.92
5      54           Buala  -8.14  159.59
6      60         Ahipara -35.17  173.17
7      73  Cabo San Lucas  22.89 -109.91
8     103         Tizimin  21.15  -88.15
9     144        Araouane  18.90   -3.53
10    164         Mankono   8.06   -6.19
11    175  Guerrero Negro  27.98 -114.06
12    176        Katsuura  35.13  140.30
13    184           Arlit  18.74    7.39
14    203          Bousse  12.66   -1.89
15    237          Jieshi  22.81  115.83
16    255      Karimnagar  18.43   79.15
17    262         Bhadrak  21.06   86.51
18    320       Taoudenni  22.68   -3.98
19    337    Saint George  37.10 -113.58
20    338     Agua Prieta  31.30 -109.57
21    339          Kitale   1.02   35.01
22    344           Bilma  18.69   12.92
23    351           Nikki   9.94    3.21
24    357         Caramay  10.18  119.24
25    360             Ilo -17.64  -71.34
26    362       Hithadhoo  -0.60   73.08
27    366            Naco  31.33 -109.95
28    385          Bassar   9.25    0.78
29    407         Lumphat  13.49  106.98
30    409     Keti Bandar  24.14   67.45
31    428            Yola   9.20   12.48
32    441           Aswan  24.09   32.91
33    459      Natitingou  10.30    1.38
34    468       Whitianga -36.83  175.70
35    494   Bamnet Narong  15.50  101.69
36    507       Yangjiang  21.85  111.97
37    510           Perth -31.93  115.83
38    534          Marzuq  14.40   46.47
39    568          Najran  17.49   44.13

In [21]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

params = {"type" : "hotel",
          "keyword" : "hotel",
          "radius" : 5000,
          "key" : g_key}

In [23]:
for index, row in hotel_df.iterrows():
    # get city name, lat, lnt from df
    lat = row["Lat"]
    lng = row["Lng"]
    city_name = row["City"]
    
    # add keyword to params dict
    params["location"] = f"{lat},{lng}"

    # assemble url and make API request
    print(f"Retrieving Results for Index {index}: {city_name}.")
    response = requests.get(base_url, params=params).json()
    
    # extract results
    results = response['results']
    
    try:
        print(f"Closest hotel in {city_name} is {results[0]['name']}.")
        hotel_df.loc[index, "Hotel Name"] = results[0]['name']

    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")
print("-------End of Seach-------")

Retrieving Results for Index 0: Esperance.
Closest hotel in Esperance is Esperance YHA.
------------
Retrieving Results for Index 1: Kidal.
Missing field/result... skipping.
------------
Retrieving Results for Index 2: Sao Filipe.
Closest hotel in Sao Filipe is Hotel Xaguate.
------------
Retrieving Results for Index 3: Danane.
Closest hotel in Danane is HÃ´tel ZAGOHI.
------------
Retrieving Results for Index 4: Kirakira.
Missing field/result... skipping.
------------
Retrieving Results for Index 5: Buala.
Closest hotel in Buala is Maringe Lagoon Lodge.
------------
Retrieving Results for Index 6: Ahipara.
Closest hotel in Ahipara is The Huts.
------------
Retrieving Results for Index 7: Cabo San Lucas.
Closest hotel in Cabo San Lucas is Villa Del Palmar Beach Resort & Spa Cabo San Lucas.
------------
Retrieving Results for Index 8: Tizimin.
Closest hotel in Tizimin is Hotel Roazi.
------------
Retrieving Results for Index 9: Araouane.
Missing field/result... skipping.
------------
Retrieving Results for Index 10: Mankono.
Closest hotel in Mankono is Hotel Cajoux.
------------
Retrieving Results for Index 11: Guerrero Negro.
Closest hotel in Guerrero Negro is Hotel TerraSal.
------------
Retrieving Results for Index 12: Katsuura.
Closest hotel in Katsuura is Katsuura Hotel Mikazuki.
------------
Retrieving Results for Index 13: Arlit.
Closest hotel in Arlit is HÃ´tel Telwa Bungalow.
------------
Retrieving Results for Index 14: Bousse.
Missing field/result... skipping.
------------
Retrieving Results for Index 15: Jieshi.
Closest hotel in Jieshi is ç»´ä¹Ÿçº³é…’åº—.
------------
Retrieving Results for Index 16: Karimnagar.
Closest hotel in Karimnagar is Hotel Swetha.
------------
Retrieving Results for Index 17: Bhadrak.
Closest hotel in Bhadrak is Hotel Orion.
------------
Retrieving Results for Index 18: Taoudenni.
Missing field/result... skipping.
------------
Retrieving Results for Index 19: Saint George.
Closest hotel in Saint George is Red Lion Hotel & Conference Center St. George.
------------
Retrieving Results for Index 20: Agua Prieta.
Closest hotel in Agua Prieta is Best Western Douglas Inn & Suites.
------------
Retrieving Results for Index 21: Kitale.
Closest hotel in Kitale is Aturukan Hotel.
------------
Retrieving Results for Index 22: Bilma.
Missing field/result... skipping.
------------
Retrieving Results for Index 23: Nikki.
Closest hotel in Nikki is Hotel John.
------------
Retrieving Results for Index 24: Caramay.
Closest hotel in Caramay is GURU PALAWAN BEACH CLUB/ PEACE&LOVE BC.
------------
Retrieving Results for Index 25: Ilo.
Closest hotel in Ilo is Torreblanca Hotel.
------------
Retrieving Results for Index 26: Hithadhoo.
Closest hotel in Hithadhoo is Pebbles Inn.
------------
Retrieving Results for Index 27: Naco.
Closest hotel in Naco is Bisbee RV park at Turquoise Valley.
------------
Retrieving Results for Index 28: Bassar.
Missing field/result... skipping.
------------
Retrieving Results for Index 29: Lumphat.
Closest hotel in Lumphat is Lumphat Homestay.
------------
Retrieving Results for Index 30: Keti Bandar.
Missing field/result... skipping.
------------
Retrieving Results for Index 31: Yola.
Closest hotel in Yola is AUN Hotel.
------------
Retrieving Results for Index 32: Aswan.
Closest hotel in Aswan is Hotel Sofitel Legend Old Cataract Aswan.
------------
Retrieving Results for Index 33: Natitingou.
Closest hotel in Natitingou is Hotel Bellevue.
------------
Retrieving Results for Index 34: Whitianga.
Closest hotel in Whitianga is Albert Number 6 Motel Whitianga.
------------
Retrieving Results for Index 35: Bamnet Narong.
Missing field/result... skipping.
------------
Retrieving Results for Index 36: Yangjiang.
Closest hotel in Yangjiang is Yangjiang Changjiang International Hotel.
------------
Retrieving Results for Index 37: Perth.
Closest hotel in Perth is The Great Southern Hotels Perth.
------------
Retrieving Results for Index 38: Marzuq.
Missing field/result... skipping.
------------
Retrieving Results for Index 39: Najran.
Missing field/result... skipping.
------------
-------End of Seach-------

In [25]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in narrowed_city_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

KeyError: 'Hotel Name'

In [34]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations)

# Add the layer to the map
fig.add_layer(markers)

# Display Map
fig

Figure(layout=FigureLayout(height='420px'))